versions.v1 = {
  name: "Evadare",
  version: "ch1",
  date: "2022",
  folder: "asset-v1/",
  looptime: 6857,
  bpm: 140,
  totalframe: 342,
  nbpolo: 7,
  bonusloopA: true,
  bonusendloopA: false,
  colBck: "#231143",
  col0: "#68388e",
  col1: "#542a82",
  col2: "#492078",
  col3: "#341a58",
  col4: "#210534",
  animearray: [
    {
      name: "1_lanturi",
      color: "68388e",
      uniqsnd: false,
    },
    {
      name: "2_jacko",
      color: "68388e",
      uniqsnd: false,
    },
    {
      name: "3_breakmask",
      color: "68388e",
      uniqsnd: true,
    },
    {
      name: "4_tim",
      color: "68388e",
      uniqsnd: true,
    },
    {
      name: "5_kah",
      color: "68388e",
      uniqsnd: true,
    },
    {
      name: "6_bass",
      color: "b43939",
      uniqsnd: false,
    },
    {
      name: "7_gasmask",
      color: "b43939",
      uniqsnd: false,
    },
    {
      name: "8_clock",
      color: "b43939",
      uniqsnd: true,
    },
    {
      name: "9_piano",
      color: "b43939",
      uniqsnd: false,
    },
    {
      name: "10_teeth",
      color: "b43939",
      uniqsnd: true,
    },
    {
      name: "11_skel",
      color: "2d846c",
      uniqsnd: true,
    },
    {
      name: "12_mumie",
      color: "2d846c",
      uniqsnd: true,
    },
    {
      name: "13_agatha",
      color: "2d846c",
      uniqsnd: false,
    },
    {
      name: "14_infectat",
      color: "2d846c",
      uniqsnd: true,
    },
    {
      name: "15_dou",
      color: "2d846c",
      uniqsnd: false,
    },
    {
      name: "16_shakala",
      color: "195a71",
      uniqsnd: true,
    },
    {
      name: "17_evadare",
      color: "195a71",
      uniqsnd: false,
    },
    {
      name: "18_stars",
      color: "195a71",
      uniqsnd: false,
    },
    {
      name: "19_samara",
      color: "195a71",
      uniqsnd: false,
    },
    {
      name: "20_aries",
      color: "195a71",
      uniqsnd: false,
    },
    {
      name: "21_organ",
      color: "2d846c",
      uniqsnd: false,
    },
    {
      name: "22_umbra",
      color: "b43939",
      uniqsnd: false,
    },
  ],
  bonusarray: [
    {
      name: "Invitat",
      src: "b1-c2-invitat-hb",
      code: "1,3,4,11,12",
      sound: "bonus-invitat",
      aspire: "aspire-invitat",
      loop: 6,
    },
    {
      name: "evadare",
      src: "b2-c2-evadare-hb",
      code: "1,6,7,14,17",
      sound: "bonus-evadare",
      aspire: "aspire-invitat",
      loop: 6,
    },
    {
      name: "galaxy",
      src: "b3-c2-galaxy-hb",
      code: "8,9,15,19,20",
      sound: "bonus-galaxy",
      aspire: "aspire-galaxy",
      loop: 6,
    },
  ],
};
versions.v2 = {
  name: "Xrun",
  version: "ch2",
  date: "2022",
  folder: gE(2172),
  looptime: 6957,
  bpm: 138,
  totalframe: 338,
  nbpolo: 7,
  bonusloopA: true,
  bonusendloopA: true,
  colBck: "#20070B",
  col0: "#863D38",
  col1: "#762C29",
  col2: "#662024",
  col3: "#49101A",
  col4: "#3FOC19",
  animearray: [
    {
      name: "1_kick",
      color: "775A39",
      uniqsnd: true,
    },
    {
      name: "2_sparrow",
      color: "775A39",
      uniqsnd: true,
    },
    {
      name: "3_woodpeckers",
      color: "775A39",
      uniqsnd: true,
    },
    {
      name: "4_crab",
      color: "775A39",
      uniqsnd: true,
    },
    {
      name: "5_drummer",
      color: "775A39",
      uniqsnd: true,
    },
    {
      name: "6_bass",
      color: "445242",
      uniqsnd: false,
    },
    {
      name: "7_xagone",
      color: "445242",
      uniqsnd: false,
    },
    {
      name: "8_bubbels",
      color: "445242",
      uniqsnd: true,
    },
    {
      name: "9_dou",
      color: "445242",
      uniqsnd: false,
    },
    {
      name: "10_elk",
      color: "445242",
      uniqsnd: true,
    },
    {
      name: "11_sticlafluier",
      color: "36484D",
      uniqsnd: false,
    },
    {
      name: "12_eyewatch",
      color: "36484D",
      uniqsnd: false,
    },
    {
      name: "13_harmo",
      color: "36484D",
      uniqsnd: false,
    },
    {
      name: "14_pearl",
      color: "36484D",
      uniqsnd: false,
    },
    {
      name: "15_brass",
      color: "36484D",
      uniqsnd: false,
    },
    {
      name: "16_capitan",
      color: "762C29",
      uniqsnd: false,
    },
    {
      name: "17_ahoy",
      color: "762C29",
      uniqsnd: true,
    },
    {
      name: "18_choir",
      color: "762C29",
      uniqsnd: false,
    },
    {
      name: "19_tragic",
      color: "762C29",
      uniqsnd: false,
    },
    {
      name: "20_siren",
      color: "762C29",
      uniqsnd: false,
    },
    {
      name: "21_hunter",
      color: "775A39",
      uniqsnd: true,
    },
    {
      name: "22_seabomb",
      color: "445242",
      uniqsnd: false,
    },
  ],
  bonusarray: [
    {
      name: "The Lost",
      src: "c2-b1-lost-hb",
      code: "1,2,6,12,16",
      sound: "bonus-lost",
      aspire: "aspire",
      loop: 6,

    },
    {
      name: "Tragic",
      src: "c2-b2-tragic-hb",
      code: "2,5,7,15,19",
      sound: "bonus-tragic",
      aspire: "aspire-tragic",
      loop: 6,
    },
    {
      name: "Trauma",
      src: "c2-b3-trauma-hb",
      code: "6,10,13,18,20",
      sound: "bonus-trauma",
      aspire: "aspire",
      loop: 6,
    },
  ],
};
versions.v3 = {
  name: "Void",
  version: "ch3",
  date: "2023",
  folder: gE(2674),
  looptime: 8e3,
  bpm: 120,
  totalframe: 384,
  nbpolo: 7,
  bonusloopA: true,
  bonusendloopA: true,
  colBck: "#3D3D3D",
  col0: "#c6c6c6",
  col1: "#727272",
  col2: "#5e5e5e",
  col3: "#2b2b2b",
  col4: "#444444",
  animearray: [
    {
      name: "1_chukuno",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "2_lanuqkicktsu",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "3_plaqque",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "4_qipqqtppsgskkskk",
      color: "727272",
      uniqsnd: true,
    },
    {
      name: "5_boomgueh",
      color: "727272",
      uniqsnd: true,
    },
    {
      name: "6_mooooqumesa",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "7_aughjaiuruskk",
      color: "727272",
      uniqsnd: true,
    },
    {
      name: "8_",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "9_072021",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "10_nightmare",
      color: "727272",
      uniqsnd: true,
    },
    {
      name: "11_ewoo",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "12_rendgen",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "13_uod",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "14_sticlaateshi",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "15_musicbox",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "16_rafe",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "17_TV",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "18_aries",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "19_accident",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "20_infectat",
      color: "727272",
      uniqsnd: true,
    },
    {
      name: "21_woppowoppowtsu",
      color: "727272",
      uniqsnd: false,
    },
    {
      name: "22_!",
      color: "727272",
      uniqsnd: false,
    },
  ],
  bonusarray: [
    {
      name: "Nightmare",
      src: "c3-b1-nightmare-hb",
      code: "2,6,11,16,19",
      sound: "bonus-nightmare",
      aspire: "aspire-nigthmare",
      loop: 6,
    },
    {
      name: "Friends?",
      src: "c3-b2-friends-hb",
      code: "1,4,6,8,12",
      sound: "bonus-friends",
      aspire: "aspire-friends",
      loop: 6,
    },
    {
      name: "Wake-Up",
      src: "c3-b3-wakeup-hb",
      code: "2,6,13,17,20",
      sound: "bonus-wakeup",
      aspire: "aspire-wakeup",
      loop: 6,
    },
  ],
};
versions.v4 = {
  name: "Full Stop Puncutation",
  version: ".",
  date: "2024",
  folder: "asset-v4/",
  looptime: 6486,
  bpm: 148,
  totalframe: 312,
  nbpolo: 7,
  bonusloopA: true,
  bonusendloopA: false,
  colBck: "#100b05",
  col0: "#CD9459",
  col1: "#CD9459",
  col2: "#382615",
  col3: "#795331",
  col4: "#ffe5c1",
  animearray: [
    {
      name: "1_ignited_drummer",
      color: "CD9459",
      uniqsnd: true,
    },
    {
      name: "2_disaster_tim",
      color: "CD9459",
      uniqsnd: true,
    },
    {
      name: "3_criminal",
      color: "CD9459",
      uniqsnd: true,
    },
    {
      name: "4_ripperface",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "5_henry",
      color: "CD9459",
      uniqsnd: true,
    },
    {
      name: "6_scarymaze",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "7_chase",
      color: "CD9459",
      uniqsnd: true,
    },
    {
      name: "8_mouth",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "9_01001001_01010100",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "10_manpig",
      color: "CD9459",
      uniqsnd: true,
    },
    {
      name: "11_aaaaaaaaaaaaaaaaaaaaaaaa",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "12_alone",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "13_brassophone",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "14_dolphin_muzzle",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "15_habdaey",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "16_ImScared",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "17_ignited_samara",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "18_phantom_rafe",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "19_sam",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "20_ø·ø ̈ùšù„ø© ø£øoù†ùšø©",
      color: "61141B",
      uniqsnd: false,
    },
    {
      name: "21_corpse",
      color: "CD9459",
      uniqsnd: false,
    },
    {
      name: "22_arsenie",
      color: "CD9459",
      uniqsnd: false,
    },
  ],
  bonusarray: [
    {
      name: "Severed",
      src: "c4-b1-severed-hb",
      code: "1,7,11,13,16",
      sound: "bonus-severed",
      aspire: "aspire-severed",
      loop: 6,
    },
    {
      name: "Darkness",
      src: "c4-b2-darkness-hb",
      code: "1,2,3,4,5",
      sound: "bonus-darkness",
      aspire: "aspire-darkness",
      loop: 4,
    },
    {
      name: "The End",
      src: "c4-b3-theend-hb",
      code: "6,14,15,21,22",
      sound: "bonus-theend",
      aspire: "aspire-theend",
      loop: 6,
    },
  ],
}